//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.DAO.Modulo1 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosDaoModulo1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosDaoModulo1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAO.DAO.Modulo1.RecursosDaoModulo1", typeof(RecursosDaoModulo1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_01_004.
        /// </summary>
        internal static string Codigo_Email_Errado {
            get {
                return ResourceManager.GetString("Codigo_Email_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_01_002.
        /// </summary>
        internal static string Codigo_Login_Errado {
            get {
                return ResourceManager.GetString("Codigo_Login_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_01_003.
        /// </summary>
        internal static string Codigo_Respuesta_Errada {
            get {
                return ResourceManager.GetString("Codigo_Respuesta_Errada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_01_001.
        /// </summary>
        internal static string Codigo_Usuario_Vacio {
            get {
                return ResourceManager.GetString("Codigo_Usuario_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo obtener la pregunta de seguridad, el email es invalido.
        /// </summary>
        internal static string Mensaje_Email_errado {
            get {
                return ResourceManager.GetString("Mensaje_Email_errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo iniciar sesion, datos erroneos.
        /// </summary>
        internal static string Mensaje_Login_Errado {
            get {
                return ResourceManager.GetString("Mensaje_Login_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo validar la pregunta, respuesta invalida.
        /// </summary>
        internal static string Mensaje_Respuesta_Errada {
            get {
                return ResourceManager.GetString("Mensaje_Respuesta_Errada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de usuario incompletos.
        /// </summary>
        internal static string Mensaje_Usuario_Vacio {
            get {
                return ResourceManager.GetString("Mensaje_Usuario_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Clave.
        /// </summary>
        internal static string Parametro_Input_Clave {
            get {
                return ResourceManager.GetString("Parametro_Input_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Correo.
        /// </summary>
        internal static string Parametro_Input_Correo {
            get {
                return ResourceManager.GetString("Parametro_Input_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Username.
        /// </summary>
        internal static string Parametro_Input_Username {
            get {
                return ResourceManager.GetString("Parametro_Input_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Usu_pregseguridad.
        /// </summary>
        internal static string Parametro_Output_PreguntaSeguridad {
            get {
                return ResourceManager.GetString("Parametro_Output_PreguntaSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Usu_respseguridad.
        /// </summary>
        internal static string Parametro_Output_RespuestaSeguridad {
            get {
                return ResourceManager.GetString("Parametro_Output_RespuestaSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Usu_apellido.
        /// </summary>
        internal static string Parametro_Output_Usu_apellido {
            get {
                return ResourceManager.GetString("Parametro_Output_Usu_apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Usu_cargo.
        /// </summary>
        internal static string Parametro_Output_Usu_cargo {
            get {
                return ResourceManager.GetString("Parametro_Output_Usu_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Usu_correo.
        /// </summary>
        internal static string Parametro_Output_Usu_correo {
            get {
                return ResourceManager.GetString("Parametro_Output_Usu_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Usu_nombre.
        /// </summary>
        internal static string Parametro_Output_Usu_nombre {
            get {
                return ResourceManager.GetString("Parametro_Output_Usu_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Usu_rol.
        /// </summary>
        internal static string Parametro_Output_Usu_rol {
            get {
                return ResourceManager.GetString("Parametro_Output_Usu_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cambiar_clave.
        /// </summary>
        internal static string Query_Cambiar_Clave {
            get {
                return ResourceManager.GetString("Query_Cambiar_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a obtener_pregunta_seguridad.
        /// </summary>
        internal static string Query_Obtener_Pregunta_Seguridad {
            get {
                return ResourceManager.GetString("Query_Obtener_Pregunta_Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar_Pregunta_Seguridad.
        /// </summary>
        internal static string Query_Validar_Pregunta_Seguridad {
            get {
                return ResourceManager.GetString("Query_Validar_Pregunta_Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a validar_correo.
        /// </summary>
        internal static string Query_ValidarCorreo {
            get {
                return ResourceManager.GetString("Query_ValidarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a validarlogin.
        /// </summary>
        internal static string Query_ValidarLogin {
            get {
                return ResourceManager.GetString("Query_ValidarLogin", resourceCulture);
            }
        }
    }
}
