//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentadores {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosGeneralPresentadores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosGeneralPresentadores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentadores.RecursosGeneralPresentadores", typeof(RecursosGeneralPresentadores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_00_004.
        /// </summary>
        internal static string Codigo_Error_InputInvalido {
            get {
                return ResourceManager.GetString("Codigo_Error_InputInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Master/menuLateral.xml.
        /// </summary>
        internal static string Direccion_XML {
            get {
                return ResourceManager.GetString("Direccion_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ^[A-Z a-z]*$.
        /// </summary>
        internal static string Expresion_Regular_Alfabeticos {
            get {
                return ResourceManager.GetString("Expresion_Regular_Alfabeticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \\w.
        /// </summary>
        internal static string Expresion_Regular_Alfanumericos {
            get {
                return ResourceManager.GetString("Expresion_Regular_Alfanumericos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \\d.
        /// </summary>
        internal static string Expresion_Regular_Numericos {
            get {
                return ResourceManager.GetString("Expresion_Regular_Numericos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy.
        /// </summary>
        internal static string Formato_Fecha {
            get {
                return ResourceManager.GetString("Formato_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 100.
        /// </summary>
        internal static string Maxima_Cantidad_Caracteres {
            get {
                return ResourceManager.GetString("Maxima_Cantidad_Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con la conexion a la base de datos, intente nuevamente.
        /// </summary>
        internal static string Mensaje_Error_BaseDatos {
            get {
                return ResourceManager.GetString("Mensaje_Error_BaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El texto ingresado es invalido, intente nuevamente.
        /// </summary>
        internal static string Mensaje_Error_InputInvalido {
            get {
                return ResourceManager.GetString("Mensaje_Error_InputInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        internal static string Minima_Cantidad_Caracteres {
            get {
                return ResourceManager.GetString("Minima_Cantidad_Caracteres", resourceCulture);
            }
        }
    }
}
