//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.DAO.Modulo5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosDAOModulo5 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosDAOModulo5() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAO.DAO.Modulo5.RecursosDAOModulo5", typeof(RecursosDAOModulo5).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROYECTO_pro_id.
        /// </summary>
        internal static string ATRIBUTO_PRO_ID {
            get {
                return ResourceManager.GetString("ATRIBUTO_PRO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_codigo.
        /// </summary>
        internal static string ATRIBUTO_REQ_CODIGO {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_descripcion.
        /// </summary>
        internal static string ATRIBUTO_REQ_DESCRIPCION {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_DESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_estatus.
        /// </summary>
        internal static string ATRIBUTO_REQ_ESTATUS {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_ESTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_id.
        /// </summary>
        internal static string ATRIBUTO_REQ_ID {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_prioridad.
        /// </summary>
        internal static string ATRIBUTO_REQ_PRIORIDAD {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_PRIORIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_tipo.
        /// </summary>
        internal static string ATRIBUTO_REQ_TIPO {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_05_006.
        /// </summary>
        internal static string CODIGO_EXCEPCION_PROYECTO_SIN_REQ_FUN {
            get {
                return ResourceManager.GetString("CODIGO_EXCEPCION_PROYECTO_SIN_REQ_FUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_05_007.
        /// </summary>
        internal static string CODIGO_EXCEPCION_PROYECTO_SIN_REQ_NOF {
            get {
                return ResourceManager.GetString("CODIGO_EXCEPCION_PROYECTO_SIN_REQ_NOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_05_005.
        /// </summary>
        internal static string CODIGO_EXCEPCION_REQUERIMIENTO_ERRADO {
            get {
                return ResourceManager.GetString("CODIGO_EXCEPCION_REQUERIMIENTO_ERRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        internal static string CONSTANTE_DELIMITADOR_DE_CODIGO {
            get {
                return ResourceManager.GetString("CONSTANTE_DELIMITADOR_DE_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF.
        /// </summary>
        internal static string CONSTANTE_RF {
            get {
                return ResourceManager.GetString("CONSTANTE_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNF.
        /// </summary>
        internal static string CONSTANTE_RNF {
            get {
                return ResourceManager.GetString("CONSTANTE_RNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_05_001.
        /// </summary>
        internal static string EXCEPCION_PRO_NO_ENC_CODIGO {
            get {
                return ResourceManager.GetString("EXCEPCION_PRO_NO_ENC_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto bajo el código especificado no ha sido encontrado o no existe.
        /// </summary>
        internal static string EXCEPCION_PRO_NO_ENC_MENSAJE {
            get {
                return ResourceManager.GetString("EXCEPCION_PRO_NO_ENC_MENSAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_05_002.
        /// </summary>
        internal static string EXCEPCION_REQ_NO_CRE_CODIGO {
            get {
                return ResourceManager.GetString("EXCEPCION_REQ_NO_CRE_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El requerimiento no ha podido ser creado correctamente.
        /// </summary>
        internal static string EXCEPCION_REQ_NO_CRE_MENSAJE {
            get {
                return ResourceManager.GetString("EXCEPCION_REQ_NO_CRE_MENSAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_05_004.
        /// </summary>
        internal static string EXCEPCION_REQ_NO_ELI_CODIGO {
            get {
                return ResourceManager.GetString("EXCEPCION_REQ_NO_ELI_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El requerimiento no ha podido ser eliminado correctamente.
        /// </summary>
        internal static string EXCEPCION_REQ_NO_ELI_MENSAJE {
            get {
                return ResourceManager.GetString("EXCEPCION_REQ_NO_ELI_MENSAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_05_003.
        /// </summary>
        internal static string EXCEPCION_REQ_NO_MOD_CODIGO {
            get {
                return ResourceManager.GetString("EXCEPCION_REQ_NO_MOD_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El requerimiento no ha podido ser modificado correctamente.
        /// </summary>
        internal static string EXCEPCION_REQ_NO_MOD_MENSAJE {
            get {
                return ResourceManager.GetString("EXCEPCION_REQ_NO_MOD_MENSAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El requerimiento no tiene proyectos no funcionales.
        /// </summary>
        internal static string MENSAJE_EXCEPCION_PROYECTO_SIN_REQ_FUN {
            get {
                return ResourceManager.GetString("MENSAJE_EXCEPCION_PROYECTO_SIN_REQ_FUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto no tiene requerimientos no funcionales.
        /// </summary>
        internal static string MENSAJE_EXCEPCION_PROYECTO_SIN_REQ_NOF {
            get {
                return ResourceManager.GetString("MENSAJE_EXCEPCION_PROYECTO_SIN_REQ_NOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El requerimiento tiene unos datos errados.
        /// </summary>
        internal static string MENSAJE_EXCEPCION_REQUERIMIENTO_ERRADO {
            get {
                return ResourceManager.GetString("MENSAJE_EXCEPCION_REQUERIMIENTO_ERRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pro_codigo.
        /// </summary>
        internal static string PARAMETRO_PRO_CODIGO {
            get {
                return ResourceManager.GetString("PARAMETRO_PRO_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pro_id.
        /// </summary>
        internal static string PARAMETRO_PRO_ID {
            get {
                return ResourceManager.GetString("PARAMETRO_PRO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PROYECTO_pro_id.
        /// </summary>
        internal static string PARAMETRO_PROYECTO_PRO_ID {
            get {
                return ResourceManager.GetString("PARAMETRO_PROYECTO_PRO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @req_codigo.
        /// </summary>
        internal static string PARAMETRO_REQ_CODIGO {
            get {
                return ResourceManager.GetString("PARAMETRO_REQ_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @req_codigo_out.
        /// </summary>
        internal static string PARAMETRO_REQ_CODIGO_OUTPUT {
            get {
                return ResourceManager.GetString("PARAMETRO_REQ_CODIGO_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @req_descripcion.
        /// </summary>
        internal static string PARAMETRO_REQ_DESCRIPCION {
            get {
                return ResourceManager.GetString("PARAMETRO_REQ_DESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @req_estatus.
        /// </summary>
        internal static string PARAMETRO_REQ_ESTATUS {
            get {
                return ResourceManager.GetString("PARAMETRO_REQ_ESTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @req_id.
        /// </summary>
        internal static string PARAMETRO_REQ_ID {
            get {
                return ResourceManager.GetString("PARAMETRO_REQ_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @req_prioridad.
        /// </summary>
        internal static string PARAMETRO_REQ_PRIORIDAD {
            get {
                return ResourceManager.GetString("PARAMETRO_REQ_PRIORIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @req_tipo.
        /// </summary>
        internal static string PARAMETRO_REQ_TIPO {
            get {
                return ResourceManager.GetString("PARAMETRO_REQ_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @resultado.
        /// </summary>
        internal static string PARAMETRO_RESULTADO {
            get {
                return ResourceManager.GetString("PARAMETRO_RESULTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_AgregarRequerimiento.
        /// </summary>
        internal static string PROCEDIMIENTO_AGREGAR_REQUERIMIENTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_AGREGAR_REQUERIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ConsultarRequerimiento.
        /// </summary>
        internal static string PROCEDIMIENTO_CONSULTAR_REQUERIMIENTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_CONSULTAR_REQUERIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ConsultarRequerimientosPorProyecto.
        /// </summary>
        internal static string PROCEDIMIENTO_CONSULTAR_REQUERIMIENTOS_POR_PROYECTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_CONSULTAR_REQUERIMIENTOS_POR_PROYECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ConsultarRequerimientosPorTipo.
        /// </summary>
        internal static string PROCEDIMIENTO_CONSULTAR_REQUERIMIENTOS_POR_TIPO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_CONSULTAR_REQUERIMIENTOS_POR_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ConsultarRequerimientosPorTipoPrioridad.
        /// </summary>
        internal static string PROCEDIMIENTO_CONSULTAR_REQUERIMIENTOS_POR_TIPO_PRIORIDAD {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_CONSULTAR_REQUERIMIENTOS_POR_TIPO_PRIORIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_EliminarRequerimiento.
        /// </summary>
        internal static string PROCEDIMIENTO_ELIMINAR_REQUERIMIENTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_ELIMINAR_REQUERIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ConsultarRequerimientosPorCodigo.
        /// </summary>
        internal static string PROCEDIMIENTO_EXISTE_REQUERIMIENTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_EXISTE_REQUERIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ModificarRequerimiento.
        /// </summary>
        internal static string PROCEDIMIENTO_MODIFICAR_REQUERIMIENTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_MODIFICAR_REQUERIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_RetornarCodigoDeRequerimiento.
        /// </summary>
        internal static string PROCEDIMIENTO_RETORNAR_CODIGO_DE_REQUERIMIENTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_RETORNAR_CODIGO_DE_REQUERIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_RetornarIdPorCodigoProyecto.
        /// </summary>
        internal static string PROCEDIMIENTO_RETORNAR_ID_POR_CODIGO_PROYECTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_RETORNAR_ID_POR_CODIGO_PROYECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_RetornarIdPorCodigoRequerimiento.
        /// </summary>
        internal static string PROCEDIMIENTO_RETORNAR_ID_POR_CODIGO_REQUERIMIENTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_RETORNAR_ID_POR_CODIGO_REQUERIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ConsultarRequerimientosPorCodigo.
        /// </summary>
        internal static string PROCEDIMIENTO_RETORNAR_REQUERIMIENTO_POR_CODIGO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_RETORNAR_REQUERIMIENTO_POR_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to funcional.
        /// </summary>
        internal static string TIPO_FUNCIONAL {
            get {
                return ResourceManager.GetString("TIPO_FUNCIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no funcional.
        /// </summary>
        internal static string TIPO_NO_FUNCIONAL {
            get {
                return ResourceManager.GetString("TIPO_NO_FUNCIONAL", resourceCulture);
            }
        }
    }
}
