//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentadores.Modulo1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosM1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosM1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentadores.Modulo1.RecursosM1", typeof(RecursosM1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_01_004.
        /// </summary>
        internal static string Codigo_Email_Errado {
            get {
                return ResourceManager.GetString("Codigo_Email_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \A(?:[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z.
        /// </summary>
        internal static string Expresion_Regular_Correo {
            get {
                return ResourceManager.GetString("Expresion_Regular_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:18329/Modulo1/PreguntaSeguridad.aspx?usuario=.
        /// </summary>
        internal static string Link_Recuperacion_Clave {
            get {
                return ResourceManager.GetString("Link_Recuperacion_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUsuario.
        /// </summary>
        internal static string LUsuario {
            get {
                return ResourceManager.GetString("LUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUsuarioRol.
        /// </summary>
        internal static string LUsuarioRol {
            get {
                return ResourceManager.GetString("LUsuarioRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Ingresar una Contraseña.
        /// </summary>
        internal static string Mensaje_AlertaClave {
            get {
                return ResourceManager.GetString("Mensaje_AlertaClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Ingresar un Correo.
        /// </summary>
        internal static string Mensaje_AlertaCorreo {
            get {
                return ResourceManager.GetString("Mensaje_AlertaCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Ingresar una Respuesta.
        /// </summary>
        internal static string Mensaje_AlertaRespuesta {
            get {
                return ResourceManager.GetString("Mensaje_AlertaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Ingresar un Username.
        /// </summary>
        internal static string Mensaje_AlertaUsername {
            get {
                return ResourceManager.GetString("Mensaje_AlertaUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe llenar los campos Vacios.
        /// </summary>
        internal static string Mensaje_campoVacio {
            get {
                return ResourceManager.GetString("Mensaje_campoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcto.
        /// </summary>
        internal static string Mensaje_Correcto {
            get {
                return ResourceManager.GetString("Mensaje_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener la pregunta de seguridad, el email es invalido.
        /// </summary>
        internal static string Mensaje_Email_errado {
            get {
                return ResourceManager.GetString("Mensaje_Email_errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error interno de la aplicacion... Por favor intente nuevamente.
        /// </summary>
        internal static string Mensaje_ErrorAplicacion {
            get {
                return ResourceManager.GetString("Mensaje_ErrorAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error no se pudo cambiar su clave... Intentelo más tarde..
        /// </summary>
        internal static string Mensaje_ErrorCambioClave {
            get {
                return ResourceManager.GetString("Mensaje_ErrorCambioClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la Carga de la Página.
        /// </summary>
        internal static string Mensaje_errorCargaPagina {
            get {
                return ResourceManager.GetString("Mensaje_errorCargaPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error con la conexion al servidor...Por favor intentelo nuevamente.
        /// </summary>
        internal static string Mensaje_ErrorConexion {
            get {
                return ResourceManager.GetString("Mensaje_ErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error con el correo del usuario, intente nuevamente.
        /// </summary>
        internal static string Mensaje_ErrorCorreo {
            get {
                return ResourceManager.GetString("Mensaje_ErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Invalido... Intentelo de nuevo.
        /// </summary>
        internal static string Mensaje_ErrorLogin {
            get {
                return ResourceManager.GetString("Mensaje_ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la Carga de la Pregunta Secreta.
        /// </summary>
        internal static string Mensaje_ErrorPregunta {
            get {
                return ResourceManager.GetString("Mensaje_ErrorPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Respuesta es Incorrecta.
        /// </summary>
        internal static string Mensaje_ErrorRespuesta {
            get {
                return ResourceManager.GetString("Mensaje_ErrorRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el Parámetro Http.
        /// </summary>
        internal static string Mensaje_parametroHttp {
            get {
                return ResourceManager.GetString("Mensaje_parametroHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        internal static string Mensaje_passwordNoCoincide {
            get {
                return ResourceManager.GetString("Mensaje_passwordNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Respuesta es Incorrecta.
        /// </summary>
        internal static string Mensaje_respuestaIncorrecta {
            get {
                return ResourceManager.GetString("Mensaje_respuestaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error con la informacion del usuario, verifique que tenga los cookies activados e intente nuevamente.
        /// </summary>
        internal static string Mensake_ErrorUsuario {
            get {
                return ResourceManager.GetString("Mensake_ErrorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se envio un mensaje a su correo... Confirme y siga los pasos.
        /// </summary>
        internal static string Parametro_CorreoEnviado {
            get {
                return ResourceManager.GetString("Parametro_CorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales.
        /// </summary>
        internal static string Parametro_Credencial {
            get {
                return ResourceManager.GetString("Parametro_Credencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?exito=1.
        /// </summary>
        internal static string Parametro_exito {
            get {
                return ResourceManager.GetString("Parametro_exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userInfo.
        /// </summary>
        internal static string Parametro_userInfo {
            get {
                return ResourceManager.GetString("Parametro_userInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuario.
        /// </summary>
        internal static string Parametro_usuario {
            get {
                return ResourceManager.GetString("Parametro_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .1*;M;3z+M~8k*+~LZU6B!Q|.!k+;=*m.
        /// </summary>
        internal static string Passphrase {
            get {
                return ResourceManager.GetString("Passphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zAo1OVejS5aWbnXwVVTr+g==.
        /// </summary>
        internal static string Pswd_Correo_Totem {
            get {
                return ResourceManager.GetString("Pswd_Correo_Totem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.aspx.
        /// </summary>
        internal static string Ventana_Default {
            get {
                return ResourceManager.GetString("Ventana_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Modulo1/Login.aspx.
        /// </summary>
        internal static string Ventana_Login {
            get {
                return ResourceManager.GetString("Ventana_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecuperacionClave.aspx.
        /// </summary>
        internal static string Ventana_RecuperacionClave {
            get {
                return ResourceManager.GetString("Ventana_RecuperacionClave", resourceCulture);
            }
        }
    }
}
