//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentadores.Modulo6 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosPresentadorModulo6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosPresentadorModulo6() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentadores.Modulo6.RecursosPresentadorModulo6", typeof(RecursosPresentadorModulo6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PresentadorAgregarActor.
        /// </summary>
        internal static string ClaseAgregarActorPresentador {
            get {
                return ResourceManager.GetString("ClaseAgregarActorPresentador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_103.
        /// </summary>
        internal static string CodigoMensajePresentadorBDException {
            get {
                return ResourceManager.GetString("CodigoMensajePresentadorBDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_101.
        /// </summary>
        internal static string CodigoMensajePresentadorException {
            get {
                return ResourceManager.GetString("CodigoMensajePresentadorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_104.
        /// </summary>
        internal static string CodigoMensajePresentadorMalicioso {
            get {
                return ResourceManager.GetString("CodigoMensajePresentadorMalicioso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_102.
        /// </summary>
        internal static string CodigoMensajePresentadorNuloException {
            get {
                return ResourceManager.GetString("CodigoMensajePresentadorNuloException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ingresado un código malicioso, por favor ingrese carácteres correctos..
        /// </summary>
        internal static string MensajeCodigoMaliciosoException {
            get {
                return ResourceManager.GetString("MensajeCodigoMaliciosoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actor agregado éxitosamente.
        /// </summary>
        internal static string MensajeExitoAgregarActor {
            get {
                return ResourceManager.GetString("MensajeExitoAgregarActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con la base de datos..
        /// </summary>
        internal static string MensajePresentadorBDException {
            get {
                return ResourceManager.GetString("MensajePresentadorBDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error general en el sistema. Por favor intente más tarde..
        /// </summary>
        internal static string MensajePresentadorException {
            get {
                return ResourceManager.GetString("MensajePresentadorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto con referencia nula u objeto vacío..
        /// </summary>
        internal static string MensajePresentadorNuloException {
            get {
                return ResourceManager.GetString("MensajePresentadorNuloException", resourceCulture);
            }
        }
    }
}
