//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaNegociosTotem.Modulo1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosLogicaModulo1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosLogicaModulo1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicaNegociosTotem.Modulo1.RecursosLogicaModulo1", typeof(RecursosLogicaModulo1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Cantidad_Intentos_Permitidos {
            get {
                return ResourceManager.GetString("Cantidad_Intentos_Permitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_01_004.
        /// </summary>
        internal static string Codigo_Email_Errado {
            get {
                return ResourceManager.GetString("Codigo_Email_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_00_001.
        /// </summary>
        internal static string Codigo_Error_Conexion_BD {
            get {
                return ResourceManager.GetString("Codigo_Error_Conexion_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_01_006.
        /// </summary>
        internal static string Codigo_Error_Envio_Correo {
            get {
                return ResourceManager.GetString("Codigo_Error_Envio_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_01_005.
        /// </summary>
        internal static string Codigo_Intentos_Fallidos {
            get {
                return ResourceManager.GetString("Codigo_Intentos_Fallidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_01_002.
        /// </summary>
        internal static string Codigo_Login_Errado {
            get {
                return ResourceManager.GetString("Codigo_Login_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_00_02.
        /// </summary>
        internal static string Codigo_Parametro_Errado {
            get {
                return ResourceManager.GetString("Codigo_Parametro_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_01_003.
        /// </summary>
        internal static string Codigo_Respuesta_Errada {
            get {
                return ResourceManager.GetString("Codigo_Respuesta_Errada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_01_001.
        /// </summary>
        internal static string Codigo_Usuario_Vacio {
            get {
                return ResourceManager.GetString("Codigo_Usuario_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTEM: Recuperacion de Clave.
        /// </summary>
        internal static string Correo_Asunto_Recuperacion_Clave {
            get {
                return ResourceManager.GetString("Correo_Asunto_Recuperacion_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si usted no solicito una recuperacion de clave, ignore este mensaje.
        /// </summary>
        internal static string Correo_Mensaje_Ignorar {
            get {
                return ResourceManager.GetString("Correo_Mensaje_Ignorar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado una solicitud de recuperacion de clave. Para seguir con el proceso, porfavor ingrese al siguiente link: .
        /// </summary>
        internal static string Correo_Mensaje_Recuperacion_Clave {
            get {
                return ResourceManager.GetString("Correo_Mensaje_Recuperacion_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totemdesarrollo@gmail.com.
        /// </summary>
        internal static string Correo_Totem {
            get {
                return ResourceManager.GetString("Correo_Totem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \A(?:[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z.
        /// </summary>
        internal static string Expresion_Regular_Correo {
            get {
                return ResourceManager.GetString("Expresion_Regular_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:22288/src/GUI/Modulo1/M1_PreguntaSeguridad.aspx?usuario=.
        /// </summary>
        internal static string Link_Recuperacion_Clave {
            get {
                return ResourceManager.GetString("Link_Recuperacion_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener la pregunta de seguridad, el email es invalido.
        /// </summary>
        internal static string Mensaje_Email_errado {
            get {
                return ResourceManager.GetString("Mensaje_Email_errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error con la Conexion en la BaseDeDatosTotem, no se pudo abrir la conexion.
        /// </summary>
        internal static string Mensaje_Error_Conexion_BD {
            get {
                return ResourceManager.GetString("Mensaje_Error_Conexion_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el envio del correo.
        /// </summary>
        internal static string Mensaje_Error_Envio_Correo {
            get {
                return ResourceManager.GetString("Mensaje_Error_Envio_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se fallo el inicio de sesion multiples veces, el usuario puede ser un bot.
        /// </summary>
        internal static string Mensaje_Intentos_Fallidos {
            get {
                return ResourceManager.GetString("Mensaje_Intentos_Fallidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo iniciar sesion, datos erroneos.
        /// </summary>
        internal static string Mensaje_Login_Errado {
            get {
                return ResourceManager.GetString("Mensaje_Login_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en un parametro del stored procedure.
        /// </summary>
        internal static string Mensaje_Parametro_Errado {
            get {
                return ResourceManager.GetString("Mensaje_Parametro_Errado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo validar la pregunta, respuesta invalida.
        /// </summary>
        internal static string Mensaje_Respuesta_Errada {
            get {
                return ResourceManager.GetString("Mensaje_Respuesta_Errada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de usuario incompletos.
        /// </summary>
        internal static string Mensaje_Usuario_Vacio {
            get {
                return ResourceManager.GetString("Mensaje_Usuario_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .1*;M;3z+M~8k*+~LZU6B!Q|.!k+;=*m.
        /// </summary>
        internal static string Passphrase {
            get {
                return ResourceManager.GetString("Passphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zAo1OVejS5aWbnXwVVTr+g==.
        /// </summary>
        internal static string Pswd_Correo_Totem {
            get {
                return ResourceManager.GetString("Pswd_Correo_Totem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        internal static string Puerto_Smtp {
            get {
                return ResourceManager.GetString("Puerto_Smtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7V-tXj%HEY0.G37U.
        /// </summary>
        internal static string Salt_Encriptado {
            get {
                return ResourceManager.GetString("Salt_Encriptado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        internal static string Servidor_Smtp {
            get {
                return ResourceManager.GetString("Servidor_Smtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256.
        /// </summary>
        internal static string Tamano_Clave {
            get {
                return ResourceManager.GetString("Tamano_Clave", resourceCulture);
            }
        }
    }
}
