//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTotem.Modulo5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo5 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo5() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTotem.Modulo5.RecursosBDModulo5", typeof(RecursosBDModulo5).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROYECTO_pro_id.
        /// </summary>
        internal static string ATRIBUTO_PRO_ID {
            get {
                return ResourceManager.GetString("ATRIBUTO_PRO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_codigo.
        /// </summary>
        internal static string ATRIBUTO_REQ_CODIGO {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_descripcion.
        /// </summary>
        internal static string ATRIBUTO_REQ_DESCRIPCION {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_DESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_estatus.
        /// </summary>
        internal static string ATRIBUTO_REQ_ESTATUS {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_ESTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_id.
        /// </summary>
        internal static string ATRIBUTO_REQ_ID {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_prioridad.
        /// </summary>
        internal static string ATRIBUTO_REQ_PRIORIDAD {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_PRIORIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to req_tipo.
        /// </summary>
        internal static string ATRIBUTO_REQ_TIPO {
            get {
                return ResourceManager.GetString("ATRIBUTO_REQ_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF.
        /// </summary>
        internal static string CONSTANTE_RF {
            get {
                return ResourceManager.GetString("CONSTANTE_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNF.
        /// </summary>
        internal static string CONSTANTE_RNF {
            get {
                return ResourceManager.GetString("CONSTANTE_RNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_05_001.
        /// </summary>
        internal static string EXCEPCION_PRO_NO_ENC_CODIGO {
            get {
                return ResourceManager.GetString("EXCEPCION_PRO_NO_ENC_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto bajo el código especificado no ha sido encontrado o no existe.
        /// </summary>
        internal static string EXCEPCION_PRO_NO_ENC_MENSAJE {
            get {
                return ResourceManager.GetString("EXCEPCION_PRO_NO_ENC_MENSAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pro_codigo.
        /// </summary>
        internal static string PARAMETRO_PRO_CODIGO {
            get {
                return ResourceManager.GetString("PARAMETRO_PRO_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pro_id.
        /// </summary>
        internal static string PARAMETRO_PRO_ID {
            get {
                return ResourceManager.GetString("PARAMETRO_PRO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_ConsultarRequerimientosPorProyecto.
        /// </summary>
        internal static string PROCEDIMIENTO_CONSULTAR_REQUERIMIENTOS_POR_PROYECTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_CONSULTAR_REQUERIMIENTOS_POR_PROYECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M5_RetornarIdPorCodigoProyecto.
        /// </summary>
        internal static string PROCEDIMIENTO_RETORNAR_ID_POR_CODIGO_PROYECTO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_RETORNAR_ID_POR_CODIGO_PROYECTO", resourceCulture);
            }
        }
    }
}
