//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTotem.Modulo7 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBaseDeDatosModulo7 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBaseDeDatosModulo7() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTotem.Modulo7.RecursosBaseDeDatosModulo7", typeof(RecursosBaseDeDatosModulo7).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_apellido.
        /// </summary>
        internal static string ApellidoUsuario {
            get {
                return ResourceManager.GetString("ApellidoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_car_nombre.
        /// </summary>
        internal static string CargoUsuario {
            get {
                return ResourceManager.GetString("CargoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_clave.
        /// </summary>
        internal static string ClaveUsuario {
            get {
                return ResourceManager.GetString("ClaveUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Source=(LocalDB)\v11.0;AttachDbFilename=C:\Users\Argenis\Desktop\totem\src\DatosTotem\BaseDeDatos\BaseDeDatosTotem.mdf;Integrated Security=True.
        /// </summary>
        internal static string conexion {
            get {
                return ResourceManager.GetString("conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_correo.
        /// </summary>
        internal static string CorreoUsuario {
            get {
                return ResourceManager.GetString("CorreoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_nombre.
        /// </summary>
        internal static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usupreguntaseguridad.
        /// </summary>
        internal static string PreguntaUsuario {
            get {
                return ResourceManager.GetString("PreguntaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConsultarUsuario.
        /// </summary>
        internal static string ProcedimientoConsultarUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CorreoUnico.
        /// </summary>
        internal static string ProcedimientoCorreoUnico {
            get {
                return ResourceManager.GetString("ProcedimientoCorreoUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InsertarUsuario.
        /// </summary>
        internal static string ProcedimientoInsertarUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoInsertarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ModificarUsuario.
        /// </summary>
        internal static string ProcedimientoModificarUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoModificarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UserNameUnico.
        /// </summary>
        internal static string ProcedimientoUsuarioUnico {
            get {
                return ResourceManager.GetString("ProcedimientoUsuarioUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT DISTINCT CAR_NOMBRE FROM CARGO, USUARIO WHERE CARGO_car_id=car_id.
        /// </summary>
        internal static string QueryCargosUsuarios {
            get {
                return ResourceManager.GetString("QueryCargosUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT usu_username,usu_nombre,usu_apellido,car_nombre
        ///   FROM USUARIO,CARGO
        ///   WHERE CARGO_car_id = car_id.
        /// </summary>
        internal static string QueryListarUsuario {
            get {
                return ResourceManager.GetString("QueryListarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT car_nombre FROM CARGO,USUARIO WHERE car_id=.
        /// </summary>
        internal static string QueryObtenerCargo {
            get {
                return ResourceManager.GetString("QueryObtenerCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM USUARIO WHERE usu_username=.
        /// </summary>
        internal static string queryObtenerUsuario {
            get {
                return ResourceManager.GetString("queryObtenerUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usurespuestaseguridad.
        /// </summary>
        internal static string RespuestaUsuario {
            get {
                return ResourceManager.GetString("RespuestaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_resultado.
        /// </summary>
        internal static string Resultadorepetido {
            get {
                return ResourceManager.GetString("Resultadorepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_rol.
        /// </summary>
        internal static string RolUsuario {
            get {
                return ResourceManager.GetString("RolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_username.
        /// </summary>
        internal static string UsernameUsuario {
            get {
                return ResourceManager.GetString("UsernameUsuario", resourceCulture);
            }
        }
    }
}
