//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentadores.Modulo3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosInterfazM3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosInterfazM3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentadores.Modulo3.RecursosInterfazM3", typeof(RecursosInterfazM3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; href=&quot;/Modulo7/DetalleUsuario.aspx?username=.
        /// </summary>
        internal static string Abrir_boton_detalleUsuario {
            get {
                return ResourceManager.GetString("Abrir_boton_detalleUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; href=&quot;AgregarInvolucrados.aspx?usuarioaeliminar=.
        /// </summary>
        internal static string Abrir_boton_eliminar {
            get {
                return ResourceManager.GetString("Abrir_boton_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-default glyphicon glyphicon-info-sign&quot; href=&quot;/Modulo2/DetallarContacto.aspx?detalle=.
        /// </summary>
        internal static string Abrir_botondetalleContacto {
            get {
                return ResourceManager.GetString("Abrir_botondetalleContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; href=&quot;ListarPersonalInvolucrado.aspx?deleteinvcontact=.
        /// </summary>
        internal static string Abrir_botoneliminarinvcontact {
            get {
                return ResourceManager.GetString("Abrir_botoneliminarinvcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; href=&quot;ListarPersonalInvolucrado.aspx?deleteinvuser=.
        /// </summary>
        internal static string Abrir_botoneliminarinvusuario {
            get {
                return ResourceManager.GetString("Abrir_botoneliminarinvusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string AbrirEtiqueta_td {
            get {
                return ResourceManager.GetString("AbrirEtiqueta_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string AbrirEtiqueta_tr {
            get {
                return ResourceManager.GetString("AbrirEtiqueta_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=.
        /// </summary>
        internal static string AbrirEtiqueta_tr_id {
            get {
                return ResourceManager.GetString("AbrirEtiqueta_tr_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involucrados no agregados.
        /// </summary>
        internal static string Alert_Involucrado_Fracaso {
            get {
                return ResourceManager.GetString("Alert_Involucrado_Fracaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-danger alert-dismissible.
        /// </summary>
        internal static string Alerta_Clase_Error {
            get {
                return ResourceManager.GetString("Alerta_Clase_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-success alert-dismissible.
        /// </summary>
        internal static string Alerta_Clase_Exito {
            get {
                return ResourceManager.GetString("Alerta_Clase_Exito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay conexion con la base de datos.
        /// </summary>
        internal static string Alerta_Conexion_Error {
            get {
                return ResourceManager.GetString("Alerta_Conexion_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto agregado exitosamente.
        /// </summary>
        internal static string Alerta_Contacto_Agregado {
            get {
                return ResourceManager.GetString("Alerta_Contacto_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Agregar Involucrado.
        /// </summary>
        internal static string Alerta_Error_AgregarInvolucrado {
            get {
                return ResourceManager.GetString("Alerta_Error_AgregarInvolucrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-label=&quot;Close&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/span&gt;&lt;/button&gt;.
        /// </summary>
        internal static string Alerta_Html {
            get {
                return ResourceManager.GetString("Alerta_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string Alerta_Html_Final {
            get {
                return ResourceManager.GetString("Alerta_Html_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        internal static string Alerta_Rol {
            get {
                return ResourceManager.GetString("Alerta_Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No has seleccionano a ningun usuario o contacto.
        /// </summary>
        internal static string Alerta_Seleccion_vacia {
            get {
                return ResourceManager.GetString("Alerta_Seleccion_vacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Totem.
        /// </summary>
        internal static string Alerta_Totem_Error {
            get {
                return ResourceManager.GetString("Alerta_Totem_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario agregado exitosamente.
        /// </summary>
        internal static string Alerta_Usuario_Agregado {
            get {
                return ResourceManager.GetString("Alerta_Usuario_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-danger alert-dismissible.
        /// </summary>
        internal static string AlertaContacto {
            get {
                return ResourceManager.GetString("AlertaContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-danger alert-dismissible.
        /// </summary>
        internal static string AlertaUsuario {
            get {
                return ResourceManager.GetString("AlertaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string Cerrar_etiqueta {
            get {
                return ResourceManager.GetString("Cerrar_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CerrarBoton {
            get {
                return ResourceManager.GetString("CerrarBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        internal static string CerrarEtiqueta_td {
            get {
                return ResourceManager.GetString("CerrarEtiqueta_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string CerrarEtiqueta_tr {
            get {
                return ResourceManager.GetString("CerrarEtiqueta_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente juridico.
        /// </summary>
        internal static string Cliente_juridico {
            get {
                return ResourceManager.GetString("Cliente_juridico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?success=true.
        /// </summary>
        internal static string Codigo_Exito_Agregar {
            get {
                return ResourceManager.GetString("Codigo_Exito_Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollo del software.
        /// </summary>
        internal static string Desarrollo_del_software {
            get {
                return ResourceManager.GetString("Desarrollo_del_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Modulo3/ListarPersonalInvolucrado.aspx.
        /// </summary>
        internal static string ListarInvolucrados {
            get {
                return ResourceManager.GetString("ListarInvolucrados", resourceCulture);
            }
        }
    }
}
