//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentadores.Modulo3 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosInterfazM3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosInterfazM3() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentadores.Modulo3.RecursosInterfazM3", typeof(RecursosInterfazM3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td&gt;.
        /// </summary>
        internal static string AbrirEtiqueta_td {
            get {
                return ResourceManager.GetString("AbrirEtiqueta_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;.
        /// </summary>
        internal static string AbrirEtiqueta_tr {
            get {
                return ResourceManager.GetString("AbrirEtiqueta_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert alert-danger alert-dismissible.
        /// </summary>
        internal static string Alerta_AgregarContacto_Fracaso {
            get {
                return ResourceManager.GetString("Alerta_AgregarContacto_Fracaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert alert-danger alert-dismissible.
        /// </summary>
        internal static string Alerta_AgregarUsuario_Fracaso {
            get {
                return ResourceManager.GetString("Alerta_AgregarUsuario_Fracaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto agregado exitosamente.
        /// </summary>
        internal static string Alerta_Contacto_Agregado {
            get {
                return ResourceManager.GetString("Alerta_Contacto_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en Agregar Involucrado.
        /// </summary>
        internal static string Alerta_Error_AgregarInvolucrado {
            get {
                return ResourceManager.GetString("Alerta_Error_AgregarInvolucrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div&gt;&lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-label=&quot;Close&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/span&gt;&lt;/button&gt;.
        /// </summary>
        internal static string Alerta_Html {
            get {
                return ResourceManager.GetString("Alerta_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/div&gt;.
        /// </summary>
        internal static string Alerta_Html_Final {
            get {
                return ResourceManager.GetString("Alerta_Html_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario agregado exitosamente.
        /// </summary>
        internal static string Alerta_Usuario_Agregado {
            get {
                return ResourceManager.GetString("Alerta_Usuario_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string CerrarBoton {
            get {
                return ResourceManager.GetString("CerrarBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/td&gt;.
        /// </summary>
        internal static string CerrarEtiqueta_td {
            get {
                return ResourceManager.GetString("CerrarEtiqueta_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/tr&gt;.
        /// </summary>
        internal static string CerrarEtiqueta_tr {
            get {
                return ResourceManager.GetString("CerrarEtiqueta_tr", resourceCulture);
            }
        }
    }
}
