//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comandos.Comandos.Modulo8 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosComandosModulo8 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosComandosModulo8() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comandos.Comandos.Modulo8.RecursosComandosModulo8", typeof(RecursosComandosModulo8).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        internal static string Ampersan {
            get {
                return ResourceManager.GetString("Ampersan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idContacto.
        /// </summary>
        internal static string AtributoAcuerdoContacto {
            get {
                return ResourceManager.GetString("AtributoAcuerdoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idUsuario.
        /// </summary>
        internal static string AtributoAcuerdoUsuario {
            get {
                return ResourceManager.GetString("AtributoAcuerdoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_id.
        /// </summary>
        internal static string AtributoContacto {
            get {
                return ResourceManager.GetString("AtributoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_id.
        /// </summary>
        internal static string AtributoUsuario {
            get {
                return ResourceManager.GetString("AtributoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\.
        /// </summary>
        internal static string Barras {
            get {
                return ResourceManager.GetString("Barras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseMinuta.tex.
        /// </summary>
        internal static string BaseMinuta {
            get {
                return ResourceManager.GetString("BaseMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_00_001.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_05.
        /// </summary>
        internal static string Codigo_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_03.
        /// </summary>
        internal static string Codigo_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_01.
        /// </summary>
        internal static string Codigo_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_04.
        /// </summary>
        internal static string Codigo_ExcepcionParametro {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_02.
        /// </summary>
        internal static string Codigo_ExcepcionSql {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdflatex.exe.
        /// </summary>
        internal static string CompiladorLatex {
            get {
                return ResourceManager.GetString("CompiladorLatex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bf Desarrollo.
        /// </summary>
        internal static string Desarrollo {
            get {
                return ResourceManager.GetString("Desarrollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Interfaz/Vista/Modulo8/docs .
        /// </summary>
        internal static string Directorio {
            get {
                return ResourceManager.GetString("Directorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end{tabular}.
        /// </summary>
        internal static string FinTabular {
            get {
                return ResourceManager.GetString("FinTabular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hline.
        /// </summary>
        internal static string hline {
            get {
                return ResourceManager.GetString("hline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin{tabular}{| p{7cm} | p{7cm} |}.
        /// </summary>
        internal static string InicioTabularPuntos {
            get {
                return ResourceManager.GetString("InicioTabularPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error con la Conexion en la BaseDeDatosTotem, no se pudo abrir la conexion.
        /// </summary>
        internal static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uno de los parametros no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje__ExcepcionParametro {
            get {
                return ResourceManager.GetString("Mensaje__ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uno de los atributos no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error se ha producido una excepcion.
        /// </summary>
        internal static string Mensaje_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error existe una referencia nula.
        /// </summary>
        internal static string Mensaje_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error existe un conflicto con la conexión a la base de datos.
        /// </summary>
        internal static string Mensaje_ExcepcionSql {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuta.tex.
        /// </summary>
        internal static string Minuta {
            get {
                return ResourceManager.GetString("Minuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fecha.
        /// </summary>
        internal static string ParametroFecha {
            get {
                return ResourceManager.GetString("ParametroFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hora.
        /// </summary>
        internal static string ParametroHora {
            get {
                return ResourceManager.GetString("ParametroHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @acu_id.
        /// </summary>
        internal static string ParametroIDAcuerdo {
            get {
                return ResourceManager.GetString("ParametroIDAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @con_id.
        /// </summary>
        internal static string ParametroIdContacto {
            get {
                return ResourceManager.GetString("ParametroIdContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @min_id.
        /// </summary>
        internal static string ParametroIDMinuta {
            get {
                return ResourceManager.GetString("ParametroIDMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pro_id.
        /// </summary>
        internal static string ParametroIdProyecto {
            get {
                return ResourceManager.GetString("ParametroIdProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_id.
        /// </summary>
        internal static string ParametroIdUsuario {
            get {
                return ResourceManager.GetString("ParametroIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -output-directory .
        /// </summary>
        internal static string ParametroLatex {
            get {
                return ResourceManager.GetString("ParametroLatex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to motivo.
        /// </summary>
        internal static string ParametroMotivo {
            get {
                return ResourceManager.GetString("ParametroMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puntos.
        /// </summary>
        internal static string ParametroPuntos {
            get {
                return ResourceManager.GetString("ParametroPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to titulo.
        /// </summary>
        internal static string ParametroTitulo {
            get {
                return ResourceManager.GetString("ParametroTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_AgregarInvolucradoCliente.
        /// </summary>
        internal static string ProcedureAgregarContactoMinuta {
            get {
                return ResourceManager.GetString("ProcedureAgregarContactoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_AgregarInvolucradoUsuario.
        /// </summary>
        internal static string ProcedureAgregarUsuarioMinuta {
            get {
                return ResourceManager.GetString("ProcedureAgregarUsuarioMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAcuerdoResponsablesContactoMinuta.
        /// </summary>
        internal static string ProcedureConsultarContactoAcuerdo {
            get {
                return ResourceManager.GetString("ProcedureConsultarContactoAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAsistenteContactoMinuta.
        /// </summary>
        internal static string ProcedureConsultarContactoMinuta {
            get {
                return ResourceManager.GetString("ProcedureConsultarContactoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAcuerdoResponsablesUsuarioMinuta.
        /// </summary>
        internal static string ProcedureConsultarUsuarioAcuerdo {
            get {
                return ResourceManager.GetString("ProcedureConsultarUsuarioAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAsistenteUsuarioMinuta.
        /// </summary>
        internal static string ProcedureConsultarUsuarioMinuta {
            get {
                return ResourceManager.GetString("ProcedureConsultarUsuarioMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarInvolucradosContactoProyecto.
        /// </summary>
        internal static string ProcedureContactoProyecto {
            get {
                return ResourceManager.GetString("ProcedureContactoProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarInvolucradosUsuarioProyecto.
        /// </summary>
        internal static string ProcedureUsuarioProyecto {
            get {
                return ResourceManager.GetString("ProcedureUsuarioProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bf Titulo.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
    }
}
