//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentadores.Modulo8 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosInterfazModulo8 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosInterfazModulo8() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentadores.Modulo8.RecursosInterfazModulo8", typeof(RecursosInterfazModulo8).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;.
        /// </summary>
        internal static string AbrirEtiquetaTd {
            get {
                return ResourceManager.GetString("AbrirEtiquetaTd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string AbrirEtiquetaTr {
            get {
                return ResourceManager.GetString("AbrirEtiquetaTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }&apos; class=&apos;btn btn-primary glyphicon glyphicon-info-sign&apos; href=&apos;DetalleMinutas.aspx?idMinuta={.
        /// </summary>
        internal static string BotonDetalle {
            get {
                return ResourceManager.GetString("BotonDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }&apos;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonDetalleCerrar {
            get {
                return ResourceManager.GetString("BotonDetalleCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a id=&apos;{.
        /// </summary>
        internal static string BotonDetalleIniciar {
            get {
                return ResourceManager.GetString("BotonDetalleIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }&apos; class=&apos;btn btn-success glyphicon glyphicon-print&apos; href=&apos;DetalleMinutas.aspx?idMinuta={.
        /// </summary>
        internal static string BotonImprimir {
            get {
                return ResourceManager.GetString("BotonImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }&apos; class=&apos;btn btn-default glyphicon glyphicon-pencil&apos; href=&apos;ModificarMinuta.aspx?idMinuta={.
        /// </summary>
        internal static string BotonModificar {
            get {
                return ResourceManager.GetString("BotonModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        internal static string CerrarEtiquetaTd {
            get {
                return ResourceManager.GetString("CerrarEtiquetaTd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string CerrarEtiquetaTr {
            get {
                return ResourceManager.GetString("CerrarEtiquetaTr", resourceCulture);
            }
        }
    }
}
