//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTotem.Modulo3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTotem.Modulo3.RecursosBDModulo3", typeof(RecursosBDModulo3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cargoNombre.
        /// </summary>
        internal static string aliasCargoNombre {
            get {
                return ResourceManager.GetString("aliasCargoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clienteJurID.
        /// </summary>
        internal static string aliasClienteJurID {
            get {
                return ResourceManager.GetString("aliasClienteJurID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clienteJurNombre.
        /// </summary>
        internal static string aliasClienteJurNombre {
            get {
                return ResourceManager.GetString("aliasClienteJurNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clienteNatID.
        /// </summary>
        internal static string aliasClienteNatID {
            get {
                return ResourceManager.GetString("aliasClienteNatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clienteNatNombre.
        /// </summary>
        internal static string aliasClienteNatNombre {
            get {
                return ResourceManager.GetString("aliasClienteNatNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contactoApellido.
        /// </summary>
        internal static string aliasContactoApellido {
            get {
                return ResourceManager.GetString("aliasContactoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contactoID.
        /// </summary>
        internal static string aliasContactoID {
            get {
                return ResourceManager.GetString("aliasContactoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contactoNombre.
        /// </summary>
        internal static string aliasContactoNombre {
            get {
                return ResourceManager.GetString("aliasContactoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuarioApellido.
        /// </summary>
        internal static string aliasUsuarioApellido {
            get {
                return ResourceManager.GetString("aliasUsuarioApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuarioID.
        /// </summary>
        internal static string aliasUsuarioID {
            get {
                return ResourceManager.GetString("aliasUsuarioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuarioNombre.
        /// </summary>
        internal static string aliasUsuarioNombre {
            get {
                return ResourceManager.GetString("aliasUsuarioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_03_005.
        /// </summary>
        internal static string Codigo_ContactoSinID {
            get {
                return ResourceManager.GetString("Codigo_ContactoSinID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_03_001.
        /// </summary>
        internal static string Codigo_Involucrado_Repetido {
            get {
                return ResourceManager.GetString("Codigo_Involucrado_Repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_03_003.
        /// </summary>
        internal static string Codigo_ListaSinInv {
            get {
                return ResourceManager.GetString("Codigo_ListaSinInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_03_002.
        /// </summary>
        internal static string Codigo_ListaSinProy {
            get {
                return ResourceManager.GetString("Codigo_ListaSinProy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_03_006.
        /// </summary>
        internal static string Codigo_ProyectoSinCod {
            get {
                return ResourceManager.GetString("Codigo_ProyectoSinCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_03_004.
        /// </summary>
        internal static string Codigo_UsuarioSinUsername {
            get {
                return ResourceManager.GetString("Codigo_UsuarioSinUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible agregar un contacto sin id.
        /// </summary>
        internal static string Mensaje_ContactoSinID {
            get {
                return ResourceManager.GetString("Mensaje_ContactoSinID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede existir un involucrado en un proyecto dos veces.
        /// </summary>
        internal static string Mensaje_Involucrado_Repetido {
            get {
                return ResourceManager.GetString("Mensaje_Involucrado_Repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible agregar una lista de involucrados vacia.
        /// </summary>
        internal static string Mensaje_ListaSinInv {
            get {
                return ResourceManager.GetString("Mensaje_ListaSinInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible agregar un involucrado a una lista que no posea un proyecto asociado.
        /// </summary>
        internal static string Mensaje_ListaSinProy {
            get {
                return ResourceManager.GetString("Mensaje_ListaSinProy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible utilizar un proyecto sin codigo para gestionar involucrados.
        /// </summary>
        internal static string Mensaje_ProyectoSinCod {
            get {
                return ResourceManager.GetString("Mensaje_ProyectoSinCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible agregar un usuario que no posea username.
        /// </summary>
        internal static string Mensaje_UsuarioSinUsername {
            get {
                return ResourceManager.GetString("Mensaje_UsuarioSinUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @proyecto_codigo.
        /// </summary>
        internal static string ParamCodProy {
            get {
                return ResourceManager.GetString("ParamCodProy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @contacto_id.
        /// </summary>
        internal static string ParamContID {
            get {
                return ResourceManager.GetString("ParamContID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @filas.
        /// </summary>
        internal static string ParamFilas {
            get {
                return ResourceManager.GetString("ParamFilas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usuario.
        /// </summary>
        internal static string ParamUsername {
            get {
                return ResourceManager.GetString("ParamUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_consultarInvCliente.
        /// </summary>
        internal static string StoredConsultarContacto {
            get {
                return ResourceManager.GetString("StoredConsultarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_consultarInvUsuario.
        /// </summary>
        internal static string StoredConsultarUsuario {
            get {
                return ResourceManager.GetString("StoredConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contar_TuplasInvContacto.
        /// </summary>
        internal static string StoredContarCliente {
            get {
                return ResourceManager.GetString("StoredContarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contar_TuplasInvUsuario.
        /// </summary>
        internal static string StoredContarUsuario {
            get {
                return ResourceManager.GetString("StoredContarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_eliminarInvCliente.
        /// </summary>
        internal static string StoredEliminarContacto {
            get {
                return ResourceManager.GetString("StoredEliminarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_eliminarInvUsuario.
        /// </summary>
        internal static string StoredEliminarUsuario {
            get {
                return ResourceManager.GetString("StoredEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_InsertarInvCliente.
        /// </summary>
        internal static string StoredInsertarCliente {
            get {
                return ResourceManager.GetString("StoredInsertarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_InsertarInvUsuario.
        /// </summary>
        internal static string StoredInsertarUsuario {
            get {
                return ResourceManager.GetString("StoredInsertarUsuario", resourceCulture);
            }
        }
    }
}
