//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comandos.Comandos.Modulo5 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosMod5Comando {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosMod5Comando() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comandos.Comandos.Modulo5.RecursosMod5Comando", typeof(RecursosMod5Comando).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Q:\totem\src\LogicaNegociosTotem\Comandos\Comandos\Modulo5\BaseRequerimientos.tex.
        /// </summary>
        internal static string ArchivoBase {
            get {
                return ResourceManager.GetString("ArchivoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Q:\totem\src\LogicaNegociosTotem\Comandos\Comandos\Modulo5\Requerimientos.tex.
        /// </summary>
        internal static string ArchivoFinal {
            get {
                return ResourceManager.GetString("ArchivoFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Q:\totem\src\LogicaNegociosTotem\Comandos\Comandos\Modulo5\Requerimientos.pdf.
        /// </summary>
        internal static string ArchivoFinalPdf {
            get {
                return ResourceManager.GetString("ArchivoFinalPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_05_006.
        /// </summary>
        internal static string codigo_excepcion_archivo_latex_no_compilado {
            get {
                return ResourceManager.GetString("codigo_excepcion_archivo_latex_no_compilado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_05_007.
        /// </summary>
        internal static string codigo_excepcion_archivo_no_encontrado {
            get {
                return ResourceManager.GetString("codigo_excepcion_archivo_no_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pdflatex.exe.
        /// </summary>
        internal static string CompiladorLatex {
            get {
                return ResourceManager.GetString("CompiladorLatex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Q:\totem\src\Interfaz\src\Vista\Modulo5\docs.
        /// </summary>
        internal static string Directorio {
            get {
                return ResourceManager.GetString("Directorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo base no se encuentra en el directorio o el archivo de salida no pudo ser abierto.
        /// </summary>
        internal static string Mensaje_Error_Archivo_Inexistente {
            get {
                return ResourceManager.GetString("Mensaje_Error_Archivo_Inexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo latex no pudo ser compilado, asegurese que el compilador de LaTex este instalado correctamente.
        /// </summary>
        internal static string Mensaje_Error_Archivo_NoCompilado {
            get {
                return ResourceManager.GetString("Mensaje_Error_Archivo_NoCompilado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -output-directory.
        /// </summary>
        internal static string ParametroLatex {
            get {
                return ResourceManager.GetString("ParametroLatex", resourceCulture);
            }
        }
    }
}
