//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTotem.Modulo2 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBaseDeDatosModulo2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBaseDeDatosModulo2() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTotem.Modulo2.RecursosBaseDeDatosModulo2", typeof(RecursosBaseDeDatosModulo2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to @idCiudad.
        /// </summary>

        internal static string ParametroBusqueda
        {
            get
            {
                return ResourceManager.GetString("ParametroBusqueda", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to @idCiudad.
        /// </summary>

        internal static string ParametroNombre
        {
            get
            {
                return ResourceManager.GetString("ParametroNombre", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to @idCiudad.
        /// </summary>

        internal static string ParametroApellido
        {
            get
            {
                return ResourceManager.GetString("ParametroApellido", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to @idCiudad.
        /// </summary>

        internal static string ParametroCorreo
        {
            get
            {
                return ResourceManager.GetString("ParametroApellido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @idCiudad.
        /// </summary>

        internal static string ParametroLugar
        {
            get
            {
                return ResourceManager.GetString("ParametroLugar", resourceCulture);
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Procedure_insertarLugar.
        /// </summary>
        internal static string ProcedureAgregarClienteNatural
        {
            get
            {
                return ResourceManager.GetString("ProcedureAgregarClienteNatural", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Procedure_insertarLugar.
        /// </summary>
        internal static string ProcedureDetallarContacto
        {
            get
            {
                return ResourceManager.GetString("ProcedureDetallarContacto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureAgregarClienteJuridico.
        /// </summary>
        internal static string ProcedureAgregarClienteJuridico
        {
            get
            {
                return ResourceManager.GetString("ProcedureAgregarClienteJuridico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ParametroRif.
        /// </summary>
        internal static string ParametroRif
        {
            get
            {
                return ResourceManager.GetString("ParametroRif", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ParametroLogo.
        /// </summary>
        internal static string ParametroLogo
        {
            get
            {
                return ResourceManager.GetString("ParametroLogo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureLlenarComboPais.
        /// </summary>
        internal static string ProcedureLlenarComboPais
        {
            get
            {
                return ResourceManager.GetString("ProcedureLlenarComboPais", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to ProcedureLlenarComboEstado.
        /// </summary>
        internal static string ProcedureLlenarComboEstado
        {
            get
            {
                return ResourceManager.GetString("ProcedureLlenarComboEstado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureLlenarComboCiudad.
        /// </summary>
        internal static string ProcedureLlenarComboCiudad
        {
            get
            {
                return ResourceManager.GetString("ProcedureLlenarComboCiudad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureObtenerDireccion.
        /// </summary>
        internal static string ProcedureObtenerDireccion
        {
            get
            {
                return ResourceManager.GetString("ProcedureObtenerDireccion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ParametroIdPais.
        /// </summary>
        internal static string ParametroIdPais
        {
            get
            {
                return ResourceManager.GetString("ParametroIdPais", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to ParametroIdEstado.
        /// </summary>
        internal static string ParametroIdEstado
        {
            get
            {
                return ResourceManager.GetString("ParametroIdEstado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ParametroIdDireccion.
        /// </summary>
        internal static string ParametroIdDireccion
        {
            get
            {
                return ResourceManager.GetString("ParametroIdDireccion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureDetallarCliente.
        /// </summary>
        internal static string ProcedureDetallarCliente
        {
            get
            {
                return ResourceManager.GetString("ProcedureDetallarCliente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ParametroIdClienteNatural.
        /// </summary>
        internal static string ParametroIdClienteNatural
        {
            get
            {
                return ResourceManager.GetString("ParametroIdClienteNatural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureConsultarDatosClienteJuridico.
        /// </summary>
        internal static string ProcedureConsultarDatosClienteJuridico
        {
            get
            {
                return ResourceManager.GetString("ProcedureConsultarDatosClienteJuridico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ParametroIdClienteJuridico.
        /// </summary>
        internal static string ParametroIdClienteJuridico
        {
            get
            {
                return ResourceManager.GetString("ParametroIdClienteJuridico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ParametroIdClienteJuridico.
        /// </summary>
        internal static string Parametroidentificador
        {
            get
            {
                return ResourceManager.GetString("Parametroidentificador", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ParametroIdClienteJuridico.
        /// </summary>
        internal static string ParametroNombren
        {
            get
            {
                return ResourceManager.GetString("ParametroNombren", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to ParametroIdClienteJuridico.
        /// </summary>
        internal static string ParametroApellidon
        {
            get
            {
                return ResourceManager.GetString("ParametroApellidon", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string similar to ParametroIdClienteJuridico.
        /// </summary>
        internal static string ParametroCorreon
        {
            get
            {
                return ResourceManager.GetString("ParametroCorreon", resourceCulture);
            }
        }




        /// <summary>
        ///   Looks up a localized string similar to ParametroIdClienteJuridico.
        /// </summary>
        internal static string ParametroLugarn
        {
            get
            {
                return ResourceManager.GetString("ParametroLugarn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ParametroCedula.
        /// </summary>
        internal static string ParametroCedula
        {
            get
            {
                return ResourceManager.GetString("ParametroCedula", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to ProcedureEliminarClienteNatural.
        /// </summary>
        internal static string ProcedureEliminarClienteNatural
        {
            get
            {
                return ResourceManager.GetString("ProcedureEliminarClienteNatural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CodigoClienteInexistente.
        /// </summary>
        internal static string CodigoClienteInexistente
        {
            get
            {
                return ResourceManager.GetString("CodigoClienteInexistente", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MensajeClienteInexistente.
        /// </summary>
        internal static string MensajeClienteInexistente
        {
            get
            {
                return ResourceManager.GetString("MensajeClienteInexistente", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to ProcedureVerificarClienteJuridico.
        /// </summary>
        internal static string ProcedureVerificarClienteJuridico
        {
            get
            {
                return ResourceManager.GetString("ProcedureVerificarClienteJuridico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureVerificarClienteNatural.
        /// </summary>
        internal static string ProcedureVerificarClienteNatural
        {
            get
            {
                return ResourceManager.GetString("ProcedureVerificarClienteNatural", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to ProcedureLlenarComboCargo.
        /// </summary>
        internal static string ProcedureLlenarComboCargo
        {
            get
            {
                return ResourceManager.GetString("ProcedureLlenarComboCargo", resourceCulture);
            }
        }

      

        /// <summary>
        ///   Looks up a localized string similar to NombreCargo.
        /// </summary>
        internal static string NombreCargo
        {
            get
            {
                return ResourceManager.GetString("NombreCargo", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to ProcedureModificarClienteJuridico.
        /// </summary>
        internal static string ProcedureModificarClienteJuridico
        {
            get
            {
                return ResourceManager.GetString("ProcedureModificarClienteJuridico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureModificarClienteNatural.
        /// </summary>
        internal static string ProcedureModificarClienteNatural
        {
            get
            {
                return ResourceManager.GetString("ProcedureModificarClienteNatural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureFkLugLug.
        /// </summary>
        internal static string ProcedureFkLugLug
        {
            get
            {
                return ResourceManager.GetString("ProcedureFkLugLug", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to NombrePais.
        /// </summary>
        internal static string NombrePais
        {
            get
            {
                return ResourceManager.GetString("NombrePais", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NombreEstado.
        /// </summary>
        internal static string NombreEstado
        {
            get
            {
                return ResourceManager.GetString("NombreEstado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NombreCiudad.
        /// </summary>
        internal static string NombreCiudad
        {
            get
            {
                return ResourceManager.GetString("NombreCiudad", resourceCulture);
            }
        }

      

        /// <summary>
        ///   Looks up a localized string similar to NombreDireccion.
        /// </summary>
        internal static string NombreDireccion
        {
            get
            {
                return ResourceManager.GetString("NombreDireccion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        internal static string Codigo
        {
            get
            {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        internal static string Numero
        {
            get
            {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NombreClienteNatural.
        /// </summary>
        internal static string NombreClienteNatural
        {
            get
            {
                return ResourceManager.GetString("NombreClienteNatural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NombreContacto.
        /// </summary>
        internal static string NombreContacto
        {
            get
            {
                return ResourceManager.GetString("NombreContacto", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to NombreContacto.
        /// </summary>
        internal static string IdCargo
        {
            get
            {
                return ResourceManager.GetString("IdCargo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureListarClientesJuridicos.
        /// </summary>
        internal static string ProcedureListarClientesJuridicos
        {
            get
            {
                return ResourceManager.GetString("ProcedureListarClientesJuridicos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProcedureListarClientesJuridicos.
        /// </summary>
        internal static string ProcedureListarClientesNaturales
        {
            get
            {
                return ResourceManager.GetString("ProcedureListarClientesNaturales", resourceCulture);
            }
        }

    }
}
