//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.DAO.Modulo8 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo8 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo8() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAO.DAO.Modulo8.RecursosBDModulo8", typeof(RecursosBDModulo8).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idContacto.
        /// </summary>
        internal static string AtributoAcuerdoContacto {
            get {
                return ResourceManager.GetString("AtributoAcuerdoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idUsuario.
        /// </summary>
        internal static string AtributoAcuerdoUsuario {
            get {
                return ResourceManager.GetString("AtributoAcuerdoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_apellido.
        /// </summary>
        internal static string AtributoApellidoContacto {
            get {
                return ResourceManager.GetString("AtributoApellidoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_apellido.
        /// </summary>
        internal static string AtributoApellidoUsuario {
            get {
                return ResourceManager.GetString("AtributoApellidoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car_nombre.
        /// </summary>
        internal static string AtributoCargoContacto {
            get {
                return ResourceManager.GetString("AtributoCargoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_rol.
        /// </summary>
        internal static string AtributoCargoUsuario {
            get {
                return ResourceManager.GetString("AtributoCargoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acu_desarrollo.
        /// </summary>
        internal static string AtributoDesarrolloAcuerdo {
            get {
                return ResourceManager.GetString("AtributoDesarrolloAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pun_desarrollo.
        /// </summary>
        internal static string AtributoDesarrolloPunto {
            get {
                return ResourceManager.GetString("AtributoDesarrolloPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acu_fecha.
        /// </summary>
        internal static string AtributoFechaAcuerdo {
            get {
                return ResourceManager.GetString("AtributoFechaAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min_fecha.
        /// </summary>
        internal static string AtributoFechaMinuta {
            get {
                return ResourceManager.GetString("AtributoFechaMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acu_id.
        /// </summary>
        internal static string AtributoIDAcuerdo {
            get {
                return ResourceManager.GetString("AtributoIDAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_id.
        /// </summary>
        internal static string AtributoIDContacto {
            get {
                return ResourceManager.GetString("AtributoIDContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min_id.
        /// </summary>
        internal static string AtributoIDMinuta {
            get {
                return ResourceManager.GetString("AtributoIDMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pun_id.
        /// </summary>
        internal static string AtributoIDPunto {
            get {
                return ResourceManager.GetString("AtributoIDPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_id.
        /// </summary>
        internal static string AtributoIDUsuario {
            get {
                return ResourceManager.GetString("AtributoIDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min_motivo.
        /// </summary>
        internal static string AtributoMotivoMinuta {
            get {
                return ResourceManager.GetString("AtributoMotivoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con_nombre.
        /// </summary>
        internal static string AtributoNombreContacto {
            get {
                return ResourceManager.GetString("AtributoNombreContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_nombre.
        /// </summary>
        internal static string AtributoNombreUsuario {
            get {
                return ResourceManager.GetString("AtributoNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min_observaciones.
        /// </summary>
        internal static string AtributoObservacionesMinuta {
            get {
                return ResourceManager.GetString("AtributoObservacionesMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pun_titulo.
        /// </summary>
        internal static string AtributoTituloPunto {
            get {
                return ResourceManager.GetString("AtributoTituloPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_05.
        /// </summary>
        internal static string Codigo_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_03.
        /// </summary>
        internal static string Codigo_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_01.
        /// </summary>
        internal static string Codigo_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_04.
        /// </summary>
        internal static string Codigo_ExcepcionParametro {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_08_02.
        /// </summary>
        internal static string Codigo_ExcepcionSql {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uno de los parametros no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje__ExcepcionParametro {
            get {
                return ResourceManager.GetString("Mensaje__ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uno de los atributos no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error se ha producido una excepcion.
        /// </summary>
        internal static string Mensaje_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error existe una referencia nula.
        /// </summary>
        internal static string Mensaje_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error existe un conflicto con la conexión a la base de datos.
        /// </summary>
        internal static string Mensaje_ExcepcionSql {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @acu_desarrollo.
        /// </summary>
        internal static string ParametroDesarrolloAcuerdo {
            get {
                return ResourceManager.GetString("ParametroDesarrolloAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pun_desarrollo.
        /// </summary>
        internal static string ParametroDesarrolloPunto {
            get {
                return ResourceManager.GetString("ParametroDesarrolloPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @acu_fecha.
        /// </summary>
        internal static string ParametroFechaAcuerdo {
            get {
                return ResourceManager.GetString("ParametroFechaAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @min_fecha.
        /// </summary>
        internal static string ParametroFechaMinuta {
            get {
                return ResourceManager.GetString("ParametroFechaMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @acu_id.
        /// </summary>
        internal static string ParametroIDAcuerdo {
            get {
                return ResourceManager.GetString("ParametroIDAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @con_id.
        /// </summary>
        internal static string ParametroIDContacto {
            get {
                return ResourceManager.GetString("ParametroIDContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @min_id.
        /// </summary>
        internal static string ParametroIDMinuta {
            get {
                return ResourceManager.GetString("ParametroIDMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pro_id.
        /// </summary>
        internal static string ParametroIDProyecto {
            get {
                return ResourceManager.GetString("ParametroIDProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pun_id.
        /// </summary>
        internal static string ParametroIDPunto {
            get {
                return ResourceManager.GetString("ParametroIDPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_id.
        /// </summary>
        internal static string ParametroIDUsuario {
            get {
                return ResourceManager.GetString("ParametroIDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MINUTA_min_id.
        /// </summary>
        internal static string ParametroMinuta {
            get {
                return ResourceManager.GetString("ParametroMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @min_motivo.
        /// </summary>
        internal static string ParametroMotivoMinuta {
            get {
                return ResourceManager.GetString("ParametroMotivoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @min_observaciones.
        /// </summary>
        internal static string ParametroObservacionesMinuta {
            get {
                return ResourceManager.GetString("ParametroObservacionesMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @min_inv_proy.
        /// </summary>
        internal static string ParametroProyectoMinuta {
            get {
                return ResourceManager.GetString("ParametroProyectoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pun_titulo.
        /// </summary>
        internal static string ParametroTituloPunto {
            get {
                return ResourceManager.GetString("ParametroTituloPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_AgregarAcuerdo.
        /// </summary>
        internal static string ProcedimientoAgregarAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_AgregarResponsablesContactoDeAcuerdos.
        /// </summary>
        internal static string ProcedimientoAgregarContactoAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarContactoAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_AgregarMinuta.
        /// </summary>
        internal static string ProcedimientoAgregarMinuta {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_AgregarPunto.
        /// </summary>
        internal static string ProcedimientoAgregarPunto {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_AgregarResponsablesUsuarioDeAcuerdos.
        /// </summary>
        internal static string ProcedimientoAgregarUsuarioAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarUsuarioAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_BuscarUltimaMinuta.
        /// </summary>
        internal static string ProcedimientoBuscarUltimaMinuta {
            get {
                return ResourceManager.GetString("ProcedimientoBuscarUltimaMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAcuerdos.
        /// </summary>
        internal static string ProcedimientoConsultarAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarContactoMinuta.
        /// </summary>
        internal static string ProcedimientoConsultarContacto {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarContacto.
        /// </summary>
        internal static string ProcedimientoConsultarContactos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarMinutasProyecto.
        /// </summary>
        internal static string ProcedimientoConsultarListaMinutas {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarListaMinutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarMinuta.
        /// </summary>
        internal static string ProcedimientoConsultarMinuta {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarPuntos.
        /// </summary>
        internal static string ProcedimientoConsultarPuntos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarUsuarioMinuta.
        /// </summary>
        internal static string ProcedimientoConsultarUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarUsuario.
        /// </summary>
        internal static string ProcedimientoConsultarUsuarios {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAcuerdoResponsablesContactoMinuta.
        /// </summary>
        internal static string ProcedimientoContactoAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoContactoAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_EliminarAcuerdo.
        /// </summary>
        internal static string ProcedimientoEliminarAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_EliminarContactoAcuerdo.
        /// </summary>
        internal static string ProcedimientoEliminarAcuerdoContacto {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarAcuerdoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_EliminarMinuta.
        /// </summary>
        internal static string ProcedimientoEliminarMinuta {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_EliminarPunto.
        /// </summary>
        internal static string ProcedimientoEliminarPunto {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ModificarMinuta.
        /// </summary>
        internal static string ProcedimientoModificarMinuta {
            get {
                return ResourceManager.GetString("ProcedimientoModificarMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ModificarPunto.
        /// </summary>
        internal static string ProcedimientoModificarPunto {
            get {
                return ResourceManager.GetString("ProcedimientoModificarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAcuerdoResponsablesMinuta.
        /// </summary>
        internal static string ProcedimientoResponsablesAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoResponsablesAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_EliminarUsuarioAcuerdo.
        /// </summary>
        internal static string ProcedimientosEliminarAcuerdoUsuario {
            get {
                return ResourceManager.GetString("ProcedimientosEliminarAcuerdoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAcuerdoResponsablesUsuarioMinuta.
        /// </summary>
        internal static string ProcedimientoUsuarioAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoUsuarioAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM MINUTA WHERE min_id =.
        /// </summary>
        internal static string Procedure1 {
            get {
                return ResourceManager.GetString("Procedure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAsistenteContactoMinuta.
        /// </summary>
        internal static string ProcedureConsultarContactoMinuta {
            get {
                return ResourceManager.GetString("ProcedureConsultarContactoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarAsistenteUsuarioMinuta.
        /// </summary>
        internal static string ProcedureConsultarUsuarioMinuta {
            get {
                return ResourceManager.GetString("ProcedureConsultarUsuarioMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarInvolucradosContactoProyecto.
        /// </summary>
        internal static string ProcedureContactoProyecto {
            get {
                return ResourceManager.GetString("ProcedureContactoProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_EliminarTodosInvolucrados.
        /// </summary>
        internal static string ProcedureEliminarInvolucradoMinuta {
            get {
                return ResourceManager.GetString("ProcedureEliminarInvolucradoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ConsultarInvolucradosUsuarioProyecto.
        /// </summary>
        internal static string ProcedureUsuarioProyecto {
            get {
                return ResourceManager.GetString("ProcedureUsuarioProyecto", resourceCulture);
            }
        }
    }
}
