//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTotem.Modulo8 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo8 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo8() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTotem.Modulo8.RecursosBDModulo8", typeof(RecursosBDModulo8).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a min_fecha.
        /// </summary>
        internal static string AtributoFechaMinuta {
            get {
                return ResourceManager.GetString("AtributoFechaMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a min_id.
        /// </summary>
        internal static string AtributoIDMinuta {
            get {
                return ResourceManager.GetString("AtributoIDMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a min_motivo.
        /// </summary>
        internal static string AtributoMotivoMinuta {
            get {
                return ResourceManager.GetString("AtributoMotivoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a min_observaciones.
        /// </summary>
        internal static string AtributoObservacionesMinuta {
            get {
                return ResourceManager.GetString("AtributoObservacionesMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @min_id.
        /// </summary>
        internal static string ParametroIDMinuta {
            get {
                return ResourceManager.GetString("ParametroIDMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarMinuta.
        /// </summary>
        internal static string ProcedimientoConsultarMinuta {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarMinuta", resourceCulture);
            }
        }
    }
}
