//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTotem.Modulo8 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo8 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo8() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosTotem.Modulo8.RecursosBDModulo8", typeof(RecursosBDModulo8).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idContacto.
        /// </summary>
        internal static string AtributoAcuerdoContacto {
            get {
                return ResourceManager.GetString("AtributoAcuerdoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idUsuario.
        /// </summary>
        internal static string AtributoAcuerdoUsuario {
            get {
                return ResourceManager.GetString("AtributoAcuerdoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a con_apellido.
        /// </summary>
        internal static string AtributoApellidoContacto {
            get {
                return ResourceManager.GetString("AtributoApellidoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_apellido.
        /// </summary>
        internal static string AtributoApellidoUsuario {
            get {
                return ResourceManager.GetString("AtributoApellidoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a car_nombre.
        /// </summary>
        internal static string AtributoCargoContacto {
            get {
                return ResourceManager.GetString("AtributoCargoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_rol.
        /// </summary>
        internal static string AtributoCargoUsuario {
            get {
                return ResourceManager.GetString("AtributoCargoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a acu_desarrollo.
        /// </summary>
        internal static string AtributoDesarrolloAcuerdo {
            get {
                return ResourceManager.GetString("AtributoDesarrolloAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pun_desarrollo.
        /// </summary>
        internal static string AtributoDesarrolloPunto {
            get {
                return ResourceManager.GetString("AtributoDesarrolloPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a acu_fecha.
        /// </summary>
        internal static string AtributoFechaAcuerdo {
            get {
                return ResourceManager.GetString("AtributoFechaAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a min_fecha.
        /// </summary>
        internal static string AtributoFechaMinuta {
            get {
                return ResourceManager.GetString("AtributoFechaMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a acu_id.
        /// </summary>
        internal static string AtributoIDAcuerdo {
            get {
                return ResourceManager.GetString("AtributoIDAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a con_id.
        /// </summary>
        internal static string AtributoIDContacto {
            get {
                return ResourceManager.GetString("AtributoIDContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a min_id.
        /// </summary>
        internal static string AtributoIDMinuta {
            get {
                return ResourceManager.GetString("AtributoIDMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pun_id.
        /// </summary>
        internal static string AtributoIDPunto {
            get {
                return ResourceManager.GetString("AtributoIDPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_id.
        /// </summary>
        internal static string AtributoIDUsuario {
            get {
                return ResourceManager.GetString("AtributoIDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a min_motivo.
        /// </summary>
        internal static string AtributoMotivoMinuta {
            get {
                return ResourceManager.GetString("AtributoMotivoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a con_nombre.
        /// </summary>
        internal static string AtributoNombreContacto {
            get {
                return ResourceManager.GetString("AtributoNombreContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_nombre.
        /// </summary>
        internal static string AtributoNombreUsuario {
            get {
                return ResourceManager.GetString("AtributoNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a min_observaciones.
        /// </summary>
        internal static string AtributoObservacionesMinuta {
            get {
                return ResourceManager.GetString("AtributoObservacionesMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pun_titulo.
        /// </summary>
        internal static string AtributoTituloPunto {
            get {
                return ResourceManager.GetString("AtributoTituloPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_08_05.
        /// </summary>
        internal static string Codigo_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_08_03.
        /// </summary>
        internal static string Codigo_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_08_01.
        /// </summary>
        internal static string Codigo_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_08_04.
        /// </summary>
        internal static string Codigo_ExcepcionParametro {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_08_02.
        /// </summary>
        internal static string Codigo_ExcepcionSql {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error uno de los parametros no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje__ExcepcionParametro {
            get {
                return ResourceManager.GetString("Mensaje__ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error uno de los atributos no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error se ha producido una excepcion.
        /// </summary>
        internal static string Mensaje_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error existe una referencia nula.
        /// </summary>
        internal static string Mensaje_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error existe un conflicto con la conexión a la base de datos.
        /// </summary>
        internal static string Mensaje_ExcepcionSql {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @acu_desarrollo.
        /// </summary>
        internal static string ParametroDesarrolloAcuerdo {
            get {
                return ResourceManager.GetString("ParametroDesarrolloAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pun_desarrollo.
        /// </summary>
        internal static string ParametroDesarrolloPunto {
            get {
                return ResourceManager.GetString("ParametroDesarrolloPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @acu_fecha.
        /// </summary>
        internal static string ParametroFechaAcuerdo {
            get {
                return ResourceManager.GetString("ParametroFechaAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @min_fecha.
        /// </summary>
        internal static string ParametroFechaMinuta {
            get {
                return ResourceManager.GetString("ParametroFechaMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @acu_id.
        /// </summary>
        internal static string ParametroIDAcuerdo {
            get {
                return ResourceManager.GetString("ParametroIDAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @con_id.
        /// </summary>
        internal static string ParametroIDContacto {
            get {
                return ResourceManager.GetString("ParametroIDContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @min_id.
        /// </summary>
        internal static string ParametroIDMinuta {
            get {
                return ResourceManager.GetString("ParametroIDMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pro_id.
        /// </summary>
        internal static string ParametroIDProyecto {
            get {
                return ResourceManager.GetString("ParametroIDProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pun_id.
        /// </summary>
        internal static string ParametroIDPunto {
            get {
                return ResourceManager.GetString("ParametroIDPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_id.
        /// </summary>
        internal static string ParametroIDUsuario {
            get {
                return ResourceManager.GetString("ParametroIDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @MINUTA_min_id.
        /// </summary>
        internal static string ParametroMinuta {
            get {
                return ResourceManager.GetString("ParametroMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @min_motivo.
        /// </summary>
        internal static string ParametroMotivoMinuta {
            get {
                return ResourceManager.GetString("ParametroMotivoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @min_observaciones.
        /// </summary>
        internal static string ParametroObservacionesMinuta {
            get {
                return ResourceManager.GetString("ParametroObservacionesMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @min_inv_proy.
        /// </summary>
        internal static string ParametroProyectoMinuta {
            get {
                return ResourceManager.GetString("ParametroProyectoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pun_titulo.
        /// </summary>
        internal static string ParametroTituloPunto {
            get {
                return ResourceManager.GetString("ParametroTituloPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_AgregarAcuerdo.
        /// </summary>
        internal static string ProcedimientoAgregarAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_AgregarResponsablesContactoDeAcuerdos.
        /// </summary>
        internal static string ProcedimientoAgregarContactoAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarContactoAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_AgregarMinuta.
        /// </summary>
        internal static string ProcedimientoAgregarMinuta {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_AgregarPunto.
        /// </summary>
        internal static string ProcedimientoAgregarPunto {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_AgregarResponsablesUsuarioDeAcuerdos.
        /// </summary>
        internal static string ProcedimientoAgregarUsuarioAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarUsuarioAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarAcuerdos.
        /// </summary>
        internal static string ProcedimientoConsultarAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarContactoMinuta.
        /// </summary>
        internal static string ProcedimientoConsultarContacto {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarContacto.
        /// </summary>
        internal static string ProcedimientoConsultarContactos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarMinutasProyecto.
        /// </summary>
        internal static string ProcedimientoConsultarListaMinutas {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarListaMinutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarMinuta.
        /// </summary>
        internal static string ProcedimientoConsultarMinuta {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarPuntos.
        /// </summary>
        internal static string ProcedimientoConsultarPuntos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarUsuarioMinuta.
        /// </summary>
        internal static string ProcedimientoConsultarUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarUsuario.
        /// </summary>
        internal static string ProcedimientoConsultarUsuarios {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarAcuerdoResponsablesContactoMinuta.
        /// </summary>
        internal static string ProcedimientoContactoAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoContactoAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_EliminarAcuerdo.
        /// </summary>
        internal static string ProcedimientoEliminarAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_EliminarContactoAcuerdo.
        /// </summary>
        internal static string ProcedimientoEliminarAcuerdoContacto {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarAcuerdoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_EliminarPunto.
        /// </summary>
        internal static string ProcedimientoEliminarPunto {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ModificarMinuta.
        /// </summary>
        internal static string ProcedimientoModificarMinuta {
            get {
                return ResourceManager.GetString("ProcedimientoModificarMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ModificarPunto.
        /// </summary>
        internal static string ProcedimientoModificarPunto {
            get {
                return ResourceManager.GetString("ProcedimientoModificarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarAcuerdoResponsablesMinuta.
        /// </summary>
        internal static string ProcedimientoResponsablesAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoResponsablesAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_EliminarUsuarioAcuerdo.
        /// </summary>
        internal static string ProcedimientosEliminarAcuerdoUsuario {
            get {
                return ResourceManager.GetString("ProcedimientosEliminarAcuerdoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarAcuerdoResponsablesUsuarioMinuta.
        /// </summary>
        internal static string ProcedimientoUsuarioAcuerdo {
            get {
                return ResourceManager.GetString("ProcedimientoUsuarioAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarAsistenteContactoMinuta.
        /// </summary>
        internal static string ProcedureConsultarContactoMinuta {
            get {
                return ResourceManager.GetString("ProcedureConsultarContactoMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_ConsultarAsistenteUsuarioMinuta.
        /// </summary>
        internal static string ProcedureConsultarUsuarioMinuta {
            get {
                return ResourceManager.GetString("ProcedureConsultarUsuarioMinuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_EliminarTodosInvolucrados.
        /// </summary>
        internal static string ProcedureEliminarInvolucradoMinuta {
            get {
                return ResourceManager.GetString("ProcedureEliminarInvolucradoMinuta", resourceCulture);
            }
        }
    }
}
