//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.DAO.Modulo6 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosDAOModulo6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosDAOModulo6() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAO.DAO.Modulo6.RecursosDAOModulo6", typeof(RecursosDAOModulo6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idActor.
        /// </summary>
        internal static string AliasIDActor {
            get {
                return ResourceManager.GetString("AliasIDActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombreActor.
        /// </summary>
        internal static string AliasNombreActor {
            get {
                return ResourceManager.GetString("AliasNombreActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DAOActor.
        /// </summary>
        internal static string ClaseDAOActor {
            get {
                return ResourceManager.GetString("ClaseDAOActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DAOCasoDeUso.
        /// </summary>
        internal static string ClaseDAOCasoDeUso {
            get {
                return ResourceManager.GetString("ClaseDAOCasoDeUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_002.
        /// </summary>
        internal static string CodigoExcepcionBDDAO {
            get {
                return ResourceManager.GetString("CodigoExcepcionBDDAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_001.
        /// </summary>
        internal static string CodigoExcepcionErrorDAO {
            get {
                return ResourceManager.GetString("CodigoExcepcionErrorDAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_003.
        /// </summary>
        internal static string CodigoExcepcionObjetoNuloDAO {
            get {
                return ResourceManager.GetString("CodigoExcepcionObjetoNuloDAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_005.
        /// </summary>
        internal static string CodigoExcepcionTipoDeDatoErroneo {
            get {
                return ResourceManager.GetString("CodigoExcepcionTipoDeDatoErroneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @codigoProyecto.
        /// </summary>
        internal static string CodigoProyecto {
            get {
                return ResourceManager.GetString("CodigoProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @codigoProyecto.
        /// </summary>
        internal static string CodigoProyecto1 {
            get {
                return ResourceManager.GetString("CodigoProyecto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @descripcion.
        /// </summary>
        internal static string DESC_ACTOR {
            get {
                return ResourceManager.GetString("DESC_ACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @descripcion.
        /// </summary>
        internal static string DESC_ACTOR1 {
            get {
                return ResourceManager.GetString("DESC_ACTOR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idactor.
        /// </summary>
        internal static string ID_ACTOR {
            get {
                return ResourceManager.GetString("ID_ACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idactor.
        /// </summary>
        internal static string ID_ACTOR1 {
            get {
                return ResourceManager.GetString("ID_ACTOR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idcasouso.
        /// </summary>
        internal static string ID_CU {
            get {
                return ResourceManager.GetString("ID_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idcasouso.
        /// </summary>
        internal static string ID_CU1 {
            get {
                return ResourceManager.GetString("ID_CU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idproyecto.
        /// </summary>
        internal static string ID_PROY {
            get {
                return ResourceManager.GetString("ID_PROY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idproyecto.
        /// </summary>
        internal static string ID_PROY_ACTOR {
            get {
                return ResourceManager.GetString("ID_PROY_ACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idproyecto.
        /// </summary>
        internal static string ID_PROY_ACTOR1 {
            get {
                return ResourceManager.GetString("ID_PROY_ACTOR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idproyecto.
        /// </summary>
        internal static string ID_PROY1 {
            get {
                return ResourceManager.GetString("ID_PROY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexión a Base de Datos al agregar el actor..
        /// </summary>
        internal static string MensajeExcepcionAgregarActorBD1 {
            get {
                return ResourceManager.GetString("MensajeExcepcionAgregarActorBD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error del sistema al agregar el actor. Por favor intente más tarde..
        /// </summary>
        internal static string MensajeExcepcionAgregarActorError1 {
            get {
                return ResourceManager.GetString("MensajeExcepcionAgregarActorError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El actor que intento agregar tiene datos vacíos..
        /// </summary>
        internal static string MensajeExcepcionAgregarActorNulo1 {
            get {
                return ResourceManager.GetString("MensajeExcepcionAgregarActorNulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexión a Base de Datos..
        /// </summary>
        internal static string MensajeExcepcionBD {
            get {
                return ResourceManager.GetString("MensajeExcepcionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el sistema. Por favor intente más tarde..
        /// </summary>
        internal static string MensajeExcepcionErrorDesconocido {
            get {
                return ResourceManager.GetString("MensajeExcepcionErrorDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia a objeto nula..
        /// </summary>
        internal static string MensajeExcepcionObjetoNulo {
            get {
                return ResourceManager.GetString("MensajeExcepcionObjetoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se generó un error al tratar de convertir un dato en otro tipo..
        /// </summary>
        internal static string MensajeTipoDeDatoErroneoException {
            get {
                return ResourceManager.GetString("MensajeTipoDeDatoErroneoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @nombre.
        /// </summary>
        internal static string NOMBRE_ACTOR {
            get {
                return ResourceManager.GetString("NOMBRE_ACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @afectado.
        /// </summary>
        internal static string Output_Afectado {
            get {
                return ResourceManager.GetString("Output_Afectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @existe.
        /// </summary>
        internal static string Output_Existe {
            get {
                return ResourceManager.GetString("Output_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR_ACTOR.
        /// </summary>
        internal static string PROCEDURE_ELIMINAR_ACTOR {
            get {
                return ResourceManager.GetString("PROCEDURE_ELIMINAR_ACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERTAR_ACTOR.
        /// </summary>
        internal static string PROCEDURE_INSERTAR_ACTOR {
            get {
                return ResourceManager.GetString("PROCEDURE_INSERTAR_ACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEER_ACTOR.
        /// </summary>
        internal static string PROCEDURE_LEER_ACTOR {
            get {
                return ResourceManager.GetString("PROCEDURE_LEER_ACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEER_ACTOR_DEL_CU.
        /// </summary>
        internal static string PROCEDURE_LEER_ACTOR_DEL_CU {
            get {
                return ResourceManager.GetString("PROCEDURE_LEER_ACTOR_DEL_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEER_CU.
        /// </summary>
        internal static string PROCEDURE_LEER_CU {
            get {
                return ResourceManager.GetString("PROCEDURE_LEER_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEER_EXTENSION.
        /// </summary>
        internal static string PROCEDURE_LEER_EXTENSION {
            get {
                return ResourceManager.GetString("PROCEDURE_LEER_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEER_PASO.
        /// </summary>
        internal static string PROCEDURE_LEER_PASO {
            get {
                return ResourceManager.GetString("PROCEDURE_LEER_PASO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEER_PRECONDICION.
        /// </summary>
        internal static string PROCEDURE_LEER_PRECONDICION {
            get {
                return ResourceManager.GetString("PROCEDURE_LEER_PRECONDICION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEER_REQUERIMIENTO_DEL_CU.
        /// </summary>
        internal static string PROCEDURE_LEER_REQUERIMIENTO_DEL_CU {
            get {
                return ResourceManager.GetString("PROCEDURE_LEER_REQUERIMIENTO_DEL_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LISTAR_CU.
        /// </summary>
        internal static string PROCEDURE_LISTAR_CU {
            get {
                return ResourceManager.GetString("PROCEDURE_LISTAR_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODIFICAR_ACTOR.
        /// </summary>
        internal static string PROCEDURE_MODIFICAR_ACTOR {
            get {
                return ResourceManager.GetString("PROCEDURE_MODIFICAR_ACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LlenarComboActores.
        /// </summary>
        internal static string ProcedureLlenarComboActores {
            get {
                return ResourceManager.GetString("ProcedureLlenarComboActores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ValidarExitenciaActor.
        /// </summary>
        internal static string ValidarExistenciaActor {
            get {
                return ResourceManager.GetString("ValidarExistenciaActor", resourceCulture);
            }
        }
    }
}
