//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comandos.Comandos.Modulo6 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosComandosModulo6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosComandosModulo6() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comandos.Comandos.Modulo6.RecursosComandosModulo6", typeof(RecursosComandosModulo6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ComandoAgregarActor.
        /// </summary>
        internal static string ClaseComandoAgregarActor {
            get {
                return ResourceManager.GetString("ClaseComandoAgregarActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ComandoConsultarActoresCombo.
        /// </summary>
        internal static string ClaseComandoConsultarActoresCombo {
            get {
                return ResourceManager.GetString("ClaseComandoConsultarActoresCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ComandoConsultarActoresXCasoDeUso.
        /// </summary>
        internal static string ClaseComandoConsultarActoresXCasoDeUso {
            get {
                return ResourceManager.GetString("ClaseComandoConsultarActoresXCasoDeUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ComandoConsultarActorXId.
        /// </summary>
        internal static string ClaseComandoConsultarActorXId {
            get {
                return ResourceManager.GetString("ClaseComandoConsultarActorXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ComandoConsultarCasosDeUsoPorActor.
        /// </summary>
        internal static string ClaseComandoConsultarCasosDeUsoPorActor {
            get {
                return ResourceManager.GetString("ClaseComandoConsultarCasosDeUsoPorActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ComandoConsultarRequerimientosXCasoDeUso.
        /// </summary>
        internal static string ClaseComandoConsultarRequerimientosPorCasoDeUso {
            get {
                return ResourceManager.GetString("ClaseComandoConsultarRequerimientosPorCasoDeUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ComandoEliminarCU.
        /// </summary>
        internal static string ClaseComandoEliminarCU {
            get {
                return ResourceManager.GetString("ClaseComandoEliminarCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ComandoListarCU.
        /// </summary>
        internal static string ClaseComandoListarCU {
            get {
                return ResourceManager.GetString("ClaseComandoListarCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ComandoVerificarExistenciaActor.
        /// </summary>
        internal static string ClaseComandoVerificarExistenciaActor {
            get {
                return ResourceManager.GetString("ClaseComandoVerificarExistenciaActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_055.
        /// </summary>
        internal static string CodigoActorNoModificado {
            get {
                return ResourceManager.GetString("CodigoActorNoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_054.
        /// </summary>
        internal static string CodigoComandoActorInexistente {
            get {
                return ResourceManager.GetString("CodigoComandoActorInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_051.
        /// </summary>
        internal static string CodigoExcepcionComandoBD {
            get {
                return ResourceManager.GetString("CodigoExcepcionComandoBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_050.
        /// </summary>
        internal static string CodigoExcepcionComandoError {
            get {
                return ResourceManager.GetString("CodigoExcepcionComandoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_052.
        /// </summary>
        internal static string CodigoExcepcionComandoObjetoNulo {
            get {
                return ResourceManager.GetString("CodigoExcepcionComandoObjetoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T_06_053.
        /// </summary>
        internal static string CodigoExcepcionComandoTipoDeDatoErroneo {
            get {
                return ResourceManager.GetString("CodigoExcepcionComandoTipoDeDatoErroneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El actor no se pudo modificar..
        /// </summary>
        internal static string MensajeActorNoModificado {
            get {
                return ResourceManager.GetString("MensajeActorNoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El actor no se encuentra registrado en la Base de Datos..
        /// </summary>
        internal static string MensajeComandoActorInexistente {
            get {
                return ResourceManager.GetString("MensajeComandoActorInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexión a Base de Datos..
        /// </summary>
        internal static string MensajeExcepcionComandoBD {
            get {
                return ResourceManager.GetString("MensajeExcepcionComandoBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error del sistema. Por favor intente más tarde..
        /// </summary>
        internal static string MensajeExcepcionComandoError {
            get {
                return ResourceManager.GetString("MensajeExcepcionComandoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto con referencia nula..
        /// </summary>
        internal static string MensajeExcepcionComandoObjetoNulo {
            get {
                return ResourceManager.GetString("MensajeExcepcionComandoObjetoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al convertir de un tipo de dato en otro..
        /// </summary>
        internal static string MensajeTipoDeDatoErroneoComandoExcepcion {
            get {
                return ResourceManager.GetString("MensajeTipoDeDatoErroneoComandoExcepcion", resourceCulture);
            }
        }
    }
}
